replicaCount: 3
deploymentName: nginx
environment: dev
labelName: nginx

image:
  repository: nginx
  pullPolicy: IfNotPresent
  tag: "1.16.1"

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80
