replicaCount: 4
deploymentName: nginx
environment: prod
labelName: nginx

image:
  repository: nginx
  pullPolicy: Always
  #pullPolicy: IfNotPresent
  tag: "1.16.1"

autoscaling:
  enabled: false
  minReplicas: 9
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80
