---
apiVersion: v1
kind: Namespace
metadata:
  name: apache2

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache2-deployment
  namespace: apache2
spec:
  selector:
    matchLabels:
      app: apache2
  replicas: 1
  template:
    metadata:
      labels:
        app: apache2
    spec:
      containers:
      - name: apache2
        image: httpd:2.4.48
        ports:
        - containerPort: 80
    
---
apiVersion: v1
kind: Service
metadata:
  name: apache2-service
  namespace: apache2
spec:
  selector:
    app: apache2
  ports:
    - port: 8098
      targetPort: 80
