---
apiVersion: v1
kind: Service
metadata:
  name: es 
  namespace: {{ .Values.namespace }}-{{ .Values.environment }}-ns
  labels:
     app: {{ .Values.appname }}
spec:
  clusterIP: NodePort
  selector:
    app: {{ .Values.appname }}
  ports:
  - name: serving
    port: 9200
  - name: node-to-node
    port: 9300
