---
apiVersion: v1
kind: Service
metadata:
  name: es 
  namespace: {{ .Values.namespace }}
  labels:
     service: {{ .Values.appname }}
spec:
  clusterIP: None
  selector:
    service: {{ .Values.appname }}
  ports:
  - name: serving
    port: 9200
  - name: node-to-node
    port: 9300
