---
apiVersion: v1
kind: Namespace
metadata:
  name: hvault 

---
apiVersion: apps/v1 
kind: Deployment
metadata:
  name: vault-deployment
  namespace: vault
spec:
  selector:
    matchLabels:
      app: vault
  replicas: 1 
  template:
    metadata:
      labels:
        app: vault
    spec:
      containers:
      - name: vault
        image: vault:1.7.3
        ports:
        - containerPort: 80

#---
#apiVersion: v1
#kind: Service
#metadata:
#  name: vault-service
#  namespace: vault
#  labels:
#    app: vault
#spec:
#  ports:
#  - port: 80
#    protocol: TCP
#  selector:
#    app: vault
##  type: LoadBalancer
