---
apiVersion: v1
kind: Namespace
metadata:
  name: nginxappargo

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: nginxappargo
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2 # Update the version of nginx from 1.14.2 to 1.16.1
        resources:
          limits:
            cpu: "1"
            memory: 200Mi
          requests:
            cpu: "0.5"
            memory: 100Mi
        ports:
        - containerPort: 80
    
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: nginxappargo
spec:
  selector:
    app: nginx
  ports:
    - port: 8088
      targetPort: 80
