---
apiVersion: v1
kind: Pod
metadata:
  name: bash-alpine
spec:
  containers:
  - image: alpine:3.12
    command:
      - /bin/sh
      - "-c"
      - "sleep 60m"
    imagePullPolicy: IfNotPresent
    name: alpine
  restartPolicy: Always
